[1.20.4] Feat: Fast vector
lambda-client/lambda pull request #46
Opened 2024-07-26 16:44 UTC by emyfops

Introduces a zero-allocation position tuple for low-level api world search

Closes #45

2024-08-17 18:40 UTC, emyfops commented
Ignore the failed workflow, it is caused by the forge bootstrap that was fixed in e5ae0dd

2024-08-19 01:53 UTC, Avanatiker requested changes

2024-08-19 01:53 UTC, Avanatiker commented on common/src/main/kotlin/com/lambda/util/world/Position.kt
> + * and the Y coordinate is stored in the middle 12 bits. This encoding allows for a maximum world size of
middle -> least significant

2024-08-19 01:53 UTC, Avanatiker commented on common/src/main/kotlin/com/lambda/util/world/WorldUtils.kt
> +        step: FastVector = 274945015809L,
magic number?

2024-08-19 01:53 UTC, Avanatiker commented on common/src/main/kotlin/com/lambda/util/world/WorldUtils.kt
> +        step: FastVector = 274945015809L,
magic number? use constants instead and explain them

2024-08-19 01:53 UTC, Avanatiker commented on common/src/main/kotlin/com/lambda/util/world/WorldUtils.kt
> +        step: FastVector = 274945015809L,
magic number?

2024-08-25 21:37 UTC, merged