[1.20.x] [All] Feat: Added elytra flight mode boost
lambda-client/lambda pull request #50
Opened 2024-08-06 14:35 UTC by Camii2407

2024-08-06 17:28 UTC, emyfops requested changes

2024-08-06 17:28 UTC, emyfops commented on common/src/main/kotlin/com/lambda/module/modules/movement/ElytraFly.kt
> +    description = "Elytra Go Brrr",
Add a real description here

2024-08-06 17:28 UTC, emyfops commented on common/src/main/kotlin/com/lambda/module/modules/movement/ElytraFly.kt
> +                addSpeed(speed)
We should create an enum of possible modes for the elytra flight

2024-08-06 17:31 UTC, Camii2407 commented on common/src/main/kotlin/com/lambda/module/modules/movement/ElytraFly.kt
> +                addSpeed(speed)
yea this was the plan i dont know how to do that yet tho

2024-08-06 17:31 UTC, Camii2407 commented on common/src/main/kotlin/com/lambda/module/modules/movement/ElytraFly.kt
> +    description = "Elytra Go Brrr",
sowwy

2024-08-06 18:39 UTC, emyfops commented
Needs testing before merge

2024-08-06 19:10 UTC, emyfops requested changes
Tested on latest grim with any value.
Flagged by Grim

2024-08-13 00:33 UTC, emyfops approved these changes
Closes #51 
Approved ready to merge

2024-08-13 00:33 UTC, emyfops commented on common/src/main/kotlin/com/lambda/module/modules/movement/ElytraFly.kt
> +    private val elytraMute by setting("Mute Elytra", false, "Mutes elytra sound")
I would've called it `mute` instead, since we already know this will be muting the sounds
Really not necessary anyway

2024-08-17 02:23 UTC, merged

2024-08-17 02:23 UTC, Avanatiker commented
Thankies @Camii2407 :cat: